version: "3.7"

services:
  mariadb:
    container_name: MetricMariaDB
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'myPassword'
      MYSQL_DATABASE: 'metric'
      MYSQL_USER: 'metricUser'
      MYSQL_PASSWORD: 'myPassword'
volumes:
  mariadb-data: